# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ptn_final_edited_on_31-01-2021.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 900)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout1_main = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout1_main.setObjectName("gridLayout1_main")
        self.comboBox3_port = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox3_port.sizePolicy().hasHeightForWidth())
        self.comboBox3_port.setSizePolicy(sizePolicy)
        self.comboBox3_port.setObjectName("comboBox3_port")
        self.gridLayout1_main.addWidget(self.comboBox3_port, 7, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(30, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout1_main.addItem(spacerItem, 6, 2, 1, 1)
        self.label3_port = QtWidgets.QLabel(self.centralwidget)
        self.label3_port.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label3_port.setIndent(-1)
        self.label3_port.setObjectName("label3_port")
        self.gridLayout1_main.addWidget(self.label3_port, 6, 1, 1, 1)
        self.label2_port_type = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label2_port_type.sizePolicy().hasHeightForWidth())
        self.label2_port_type.setSizePolicy(sizePolicy)
        self.label2_port_type.setScaledContents(False)
        self.label2_port_type.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label2_port_type.setIndent(-1)
        self.label2_port_type.setObjectName("label2_port_type")
        self.gridLayout1_main.addWidget(self.label2_port_type, 6, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/QtResourceFiles/images/checked.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout1_main.addWidget(self.pushButton, 7, 5, 1, 2)
        self.horizontalLayout_delay = QtWidgets.QHBoxLayout()
        self.horizontalLayout_delay.setObjectName("horizontalLayout_delay")
        self.label5_delay = QtWidgets.QLabel(self.centralwidget)
        self.label5_delay.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label5_delay.setObjectName("label5_delay")
        self.horizontalLayout_delay.addWidget(self.label5_delay)
        self.comboBox5_delay = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox5_delay.setEditable(False)
        self.comboBox5_delay.setObjectName("comboBox5_delay")
        self.comboBox5_delay.addItem("")
        self.comboBox5_delay.addItem("")
        self.horizontalLayout_delay.addWidget(self.comboBox5_delay)
        self.gridLayout1_main.addLayout(self.horizontalLayout_delay, 6, 5, 1, 1)
        self.comboBox4_display = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox4_display.sizePolicy().hasHeightForWidth())
        self.comboBox4_display.setSizePolicy(sizePolicy)
        self.comboBox4_display.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.comboBox4_display.setObjectName("comboBox4_display")
        self.gridLayout1_main.addWidget(self.comboBox4_display, 7, 3, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout1_main.addWidget(self.progressBar, 6, 6, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout1_main.addWidget(self.textBrowser, 9, 0, 1, 7)
        self.comboBox2_port_type = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox2_port_type.sizePolicy().hasHeightForWidth())
        self.comboBox2_port_type.setSizePolicy(sizePolicy)
        self.comboBox2_port_type.setEditable(False)
        self.comboBox2_port_type.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.comboBox2_port_type.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.comboBox2_port_type.setFrame(True)
        self.comboBox2_port_type.setObjectName("comboBox2_port_type")
        self.gridLayout1_main.addWidget(self.comboBox2_port_type, 7, 0, 1, 1)
        self.groupBox_monitor = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_monitor.sizePolicy().hasHeightForWidth())
        self.groupBox_monitor.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.groupBox_monitor.setFont(font)
        self.groupBox_monitor.setObjectName("groupBox_monitor")
        self.gridLayout3_monitor = QtWidgets.QGridLayout(self.groupBox_monitor)
        self.gridLayout3_monitor.setObjectName("gridLayout3_monitor")
        self.radioButton2_system = QtWidgets.QRadioButton(self.groupBox_monitor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton2_system.sizePolicy().hasHeightForWidth())
        self.radioButton2_system.setSizePolicy(sizePolicy)
        self.radioButton2_system.setObjectName("radioButton2_system")
        self.gridLayout3_monitor.addWidget(self.radioButton2_system, 1, 0, 1, 1)
        self.radioButton4_command = QtWidgets.QRadioButton(self.groupBox_monitor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton4_command.sizePolicy().hasHeightForWidth())
        self.radioButton4_command.setSizePolicy(sizePolicy)
        self.radioButton4_command.setObjectName("radioButton4_command")
        self.gridLayout3_monitor.addWidget(self.radioButton4_command, 1, 1, 1, 1)
        self.radioButton1_port = QtWidgets.QRadioButton(self.groupBox_monitor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton1_port.sizePolicy().hasHeightForWidth())
        self.radioButton1_port.setSizePolicy(sizePolicy)
        self.radioButton1_port.setChecked(True)
        self.radioButton1_port.setObjectName("radioButton1_port")
        self.gridLayout3_monitor.addWidget(self.radioButton1_port, 0, 0, 1, 1)
        self.radioButton3_ports_list = QtWidgets.QRadioButton(self.groupBox_monitor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton3_ports_list.sizePolicy().hasHeightForWidth())
        self.radioButton3_ports_list.setSizePolicy(sizePolicy)
        self.radioButton3_ports_list.setObjectName("radioButton3_ports_list")
        self.gridLayout3_monitor.addWidget(self.radioButton3_ports_list, 0, 1, 1, 1)
        self.gridLayout1_main.addWidget(self.groupBox_monitor, 1, 3, 4, 1)
        self.label4_display = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label4_display.sizePolicy().hasHeightForWidth())
        self.label4_display.setSizePolicy(sizePolicy)
        self.label4_display.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label4_display.setIndent(-1)
        self.label4_display.setObjectName("label4_display")
        self.gridLayout1_main.addWidget(self.label4_display, 6, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(107, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout1_main.addItem(spacerItem1, 8, 5, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(30, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout1_main.addItem(spacerItem2, 6, 4, 1, 1)
        self.gridLayout3_line_edits = QtWidgets.QGridLayout()
        self.gridLayout3_line_edits.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout3_line_edits.setHorizontalSpacing(7)
        self.gridLayout3_line_edits.setVerticalSpacing(0)
        self.gridLayout3_line_edits.setObjectName("gridLayout3_line_edits")
        self.lineEdit2_command = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit2_command.setClearButtonEnabled(True)
        self.lineEdit2_command.setObjectName("lineEdit2_command")
        self.gridLayout3_line_edits.addWidget(self.lineEdit2_command, 2, 0, 1, 1)
        self.lineEdit1_ports_list = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit1_ports_list.sizePolicy().hasHeightForWidth())
        self.lineEdit1_ports_list.setSizePolicy(sizePolicy)
        self.lineEdit1_ports_list.setToolTip("")
        self.lineEdit1_ports_list.setStatusTip("")
        self.lineEdit1_ports_list.setWhatsThis("")
        self.lineEdit1_ports_list.setDragEnabled(False)
        self.lineEdit1_ports_list.setClearButtonEnabled(True)
        self.lineEdit1_ports_list.setObjectName("lineEdit1_ports_list")
        self.gridLayout3_line_edits.addWidget(self.lineEdit1_ports_list, 1, 0, 1, 1)
        self.gridLayout1_main.addLayout(self.gridLayout3_line_edits, 2, 5, 3, 2)
        self.gridLayout2_node_ip = QtWidgets.QGridLayout()
        self.gridLayout2_node_ip.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout2_node_ip.setHorizontalSpacing(0)
        self.gridLayout2_node_ip.setVerticalSpacing(7)
        self.gridLayout2_node_ip.setObjectName("gridLayout2_node_ip")
        self.comboBox1_node_ip = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox1_node_ip.sizePolicy().hasHeightForWidth())
        self.comboBox1_node_ip.setSizePolicy(sizePolicy)
        self.comboBox1_node_ip.setEditable(True)
        self.comboBox1_node_ip.setMaxVisibleItems(40)
        self.comboBox1_node_ip.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.comboBox1_node_ip.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox1_node_ip.setFrame(True)
        self.comboBox1_node_ip.setObjectName("comboBox1_node_ip")
        self.gridLayout2_node_ip.addWidget(self.comboBox1_node_ip, 2, 0, 1, 1)
        self.label1_node_ip = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1_node_ip.sizePolicy().hasHeightForWidth())
        self.label1_node_ip.setSizePolicy(sizePolicy)
        self.label1_node_ip.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label1_node_ip.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label1_node_ip.setObjectName("label1_node_ip")
        self.gridLayout2_node_ip.addWidget(self.label1_node_ip, 1, 0, 1, 1)
        self.gridLayout1_main.addLayout(self.gridLayout2_node_ip, 2, 0, 2, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAlt_4 = QtWidgets.QAction(MainWindow)
        self.actionAlt_4.setObjectName("actionAlt_4")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/QtResourceFiles/images/import-csv.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon1)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/QtResourceFiles/images/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon2)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.radioButton1_port.toggled['bool'].connect(self.label2_port_type.setVisible)
        self.radioButton1_port.toggled['bool'].connect(self.comboBox2_port_type.setVisible)
        self.radioButton1_port.toggled['bool'].connect(self.label3_port.setVisible)
        self.radioButton1_port.toggled['bool'].connect(self.comboBox3_port.setVisible)
        self.radioButton4_command.toggled['bool'].connect(self.label4_display.setHidden)
        self.radioButton4_command.toggled['bool'].connect(self.comboBox4_display.setHidden)
        self.radioButton3_ports_list.toggled['bool'].connect(self.lineEdit1_ports_list.setVisible)
        self.radioButton4_command.toggled['bool'].connect(self.lineEdit2_command.setVisible)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PTN NMS"))
        self.label3_port.setText(_translate("MainWindow", "Port"))
        self.label2_port_type.setText(_translate("MainWindow", "Port Type"))
        self.pushButton.setText(_translate("MainWindow", "OK"))
        self.pushButton.setShortcut(_translate("MainWindow", "Return"))
        self.label5_delay.setText(_translate("MainWindow", "Read delay"))
        self.comboBox5_delay.setCurrentText(_translate("MainWindow", "min"))
        self.comboBox5_delay.setItemText(0, _translate("MainWindow", "min"))
        self.comboBox5_delay.setItemText(1, _translate("MainWindow", "max"))
        self.groupBox_monitor.setTitle(_translate("MainWindow", "Monitor"))
        self.radioButton2_system.setText(_translate("MainWindow", "system"))
        self.radioButton4_command.setText(_translate("MainWindow", "command"))
        self.radioButton1_port.setText(_translate("MainWindow", "port"))
        self.radioButton3_ports_list.setText(_translate("MainWindow", "ports list"))
        self.label4_display.setText(_translate("MainWindow", "Display"))
        self.lineEdit2_command.setPlaceholderText(_translate("MainWindow", "Enter command"))
        self.lineEdit1_ports_list.setPlaceholderText(_translate("MainWindow", "List of ports eg: 1.1 2.1 3.1.2000"))
        self.label1_node_ip.setText(_translate("MainWindow", "Node IP"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionAlt_4.setText(_translate("MainWindow", "Alt+4"))
        self.actionOpen.setText(_translate("MainWindow", "Import Nodes.csv"))
        self.actionExit.setText(_translate("MainWindow", "Close"))
import ptn_images_rc
